# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce288495229eb7f36ec80ed0a1027cbf3c18abd5c362a11338a41e4e9ba90a5a2fa3c8e84ecf61cf6ce9bb70b283476239ae1f61f9a079c37695e4683c8e9729

test:
  secret_key_base: eb063c4bf3862333c9fb67a2c44728f3b0dc881ea9d3869fbc03292b3b95f47155965408e69cec1e67bc8a69feaf87cdc46060d649f027afda65ef3eb389465b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
